name: Custom legal scan
description:  automate legal scan
inputs:
  org_repo:
    description: Organization and Repo for custome legal scan
    default: ${{ github.repository }}
    required: true
  github_token:
    description: get token
    required: true
    default: ${{ github_token }}

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: pip

    - name: Install python dependencies
      shell: bash
      run: |
        python3 -m venv ${{ github.action_path }}/.venv
        source ${{ github.action_path }}/.venv/bin/activate
        pip3 install -r ${{github.action_path }}/requirement.txt

    - name: Run script
      shell: bash
      env:
        ORG_REPO: ${{ inputs.org_repo }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        source '${{ github.action_path }}/.venv/bin/activate'
        python3 ${{ github.action_path }}/main.py
